### ISSUE TITLE
Improve readability and ideally PEP8 

### ISSUE THREAD

**Issue by ngg1995** [Institute-for-Risk-and-Uncertainty/pba-for-python#8]
https://www.python.org/dev/peps/pep-0008/

**Comment by JCSadeghi** [comment]
Hi Nick,

The following workflow might be helpful, it will automate this for you:
https://github.com/JCSadeghi/PyIPM/blob/master/.github/workflows/pre-commit.yml

(explained here: https://github.com/pre-commit/action)

Regards,
Jon
